### ISSUE TITLE
How are labels transfomed for the tiff output?

### ISSUE THREAD

**Issue by Asheeshkrsharma** [MuxLi/Approximating-shapes-in-images-with-low-complexity-polygons#1]
Hi @MuxLi

Great work. I was going through the code, and was trying to use the raw output (*.txt), which is stored in a different coordinate system. Can you describe, how exactly is the transformation is being done. For reference, here is the tiff output overlay over a map:

![merge](https://user-images.githubusercontent.com/7055704/102924251-35f6c200-44b7-11eb-8399-cd4fda8acabf.jpeg)

However, the overlay I create with the text file looks like this:

![textOut](https://user-images.githubusercontent.com/7055704/102924421-8a9a3d00-44b7-11eb-8f8d-06aebc34f02d.png)

This might a silly question. Thanks for your help.

Asheesh

**Comment by Asheeshkrsharma** [comment]
Solved the problem. In function `find_pixels_inside_facet` 
Found this comment:
> The coordinates system: origin (0.0, 0.0) is set at the center of pixel (rows-1, 0), with y-axis pointing upwards. Therefore the pixel (rows-1, 0) spans the area of [-0.5, 0.5) X [-0.5, 0.5). This function records the set of coordinates of pixel centers. 

So the pixel coordinates had to be simply flipped. Origin bottom left to top left.

Thanks anyways for the wonderfull research.

**Comment by MuxLi** [comment]
> Solved the problem. In function `find_pixels_inside_facet`
> Found this comment:
> 
> > The coordinates system: origin (0.0, 0.0) is set at the center of pixel (rows-1, 0), with y-axis pointing upwards. Therefore the pixel (rows-1, 0) spans the area of [-0.5, 0.5) X [-0.5, 0.5). This function records the set of coordinates of pixel centers.
> 
> So the pixel coordinates had to be simply flipped. Origin bottom left to top left.
> 
> Thanks anyways for the wonderfull research.

Sorry for the late response. Great that you digged out the comment!
